# Graph Theory on Taste Connectivity

In [1]:
from IPython.core import display as ICD
import pandas as pd
import glob, os
import seaborn as sns
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt 
from scipy.stats import norm 
import networkx as nx
from sklearn.metrics.cluster import normalized_mutual_info_score

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

## Setup Input

The data is a `.csv` file

In [10]:
print('[INFO] loading the averaged multisite brainwave frequency data into a dataframe...\n')
frequency_file='drive/My Drive/Projects/pilot_mouse_connectivity/taste_data/output_data/averaged_regions_data.csv'

data_df = pd.read_csv(frequency_file,index_col="Unnamed: 0")
# replace infinite values with nan
data_df.replace([np.inf, -np.inf], np.nan)
# fill nan values with column average
data_df.fillna(data_df.mean(axis=1), inplace=True)
data_df.head()

[INFO] loading the averaged multisite brainwave frequency data into a dataframe...

   PFC gamma  VTA gamma  BLA gamma  ...  mouse id  Time (s)  Drinking
0 -49.699707 -50.013364 -49.557746  ...         1         0         0
1 -51.721838 -53.111148 -51.099442  ...         1         1         0
2 -49.565381 -50.669767 -49.163759  ...         1         2         0
3 -50.186694 -53.824757 -52.278485  ...         1         3         0
4 -47.717764 -49.649786 -50.033902  ...         1         4         0

[5 rows x 19 columns]

In [36]:
#set individual subject dataframes 
m1_data=data_df.loc[data_df['mouse id'] == 1 ]
m1_data.set_index("Time (s)", inplace=True)
m1_data.drop("mouse id",inplace=True,axis=1)
m2_data=data_df.loc[data_df['mouse id']==2]
m2_data.set_index("Time (s)", inplace=True)
m2_data.drop(["mouse id"],inplace=True,axis=1)
m3_data=data_df.loc[data_df['mouse id']==3]
m3_data.set_index("Time (s)", inplace=True)
m3_data.drop(["mouse id"],inplace=True, axis=1)
ICD.display(m1_data.tail())
ICD.display(m2_data.tail())
ICD.display(m3_data.tail())

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

          PFC gamma  VTA gamma  BLA gamma  ...  BLA delta  NAc delta  Drinking
Time (s)                                   ...
3595     -48.322812 -54.322065 -51.443575  ... -22.041923 -22.634952         1
3596     -46.106294 -54.595171 -52.063411  ... -25.667961 -24.305847         1
3597     -51.759455 -55.274748 -51.236035  ... -24.593462 -24.766924         1
3598     -51.880482 -54.267459 -49.676478  ... -29.754822 -30.625778         1
3599     -52.149567 -54.188309 -51.511716  ... -29.597015 -29.739259         1

[5 rows x 17 columns]

          PFC gamma  VTA gamma  BLA gamma  ...  BLA delta  NAc delta  Drinking
Time (s)                                   ...
3595     -51.956442 -57.771575 -44.730954  ... -34.422676 -37.820254         0
3596     -53.317806 -56.060108 -44.793108  ... -31.285063 -41.406677         0
3597     -53.842257 -55.792726 -44.465267  ... -45.626156 -36.739426         0
3598     -51.651171 -56.145660 -44.433011  ... -19.745683 -26.721640         0
3599     -53.332292 -55.965370 -44.549175  ... -34.823073 -57.898327         0

[5 rows x 17 columns]

          PFC gamma  VTA gamma  BLA gamma  ...  BLA delta  NAc delta  Drinking
Time (s)                                   ...
3595     -55.207063 -57.522484 -53.095205  ... -40.467348 -36.282191         0
3596     -54.415735 -56.615192 -54.009244  ... -29.257676 -30.343914         0
3597     -52.555726 -56.450039 -52.200188  ... -34.945305 -31.609310         0
3598     -55.372531 -60.499780 -52.803849  ... -39.703186 -37.014769         0
3599     -55.439892 -59.657819 -54.061182  ... -43.430489 -40.215353         0

[5 rows x 17 columns]

## Make Correlation Matrices

In [43]:
# making correlation matrices
data_dict={"M1": {"data": m1_data}, "M2": {"data": m2_data}, "M3":{"data": m3_data}}
print("[INFO] Making correlation matrices for subjects and adding to the data dictionary.")
for subj_id in data_dict:
    df=data_dict[subj_id]["data"]
    cor_matrix = df.corr()
    data_dict[subj_id]["corr"] = cor_matrix   

# view dictionary
#data_dict.items()

[INFO] Making correlation matrices for subjects and adding to the data dictionary.

In [0]:
"""
 Inputs a graph
 
 Returns a correlation matrix with only positive correlations
"""
def create_corr_network_5(G, corr_direction, min_correlation):

    ##Creates a copy of the graph
    H = G.copy()
    
    ##Checks all the edges and removes some based on corr_direction
    for stock1, stock2, weight in list(G.edges(data=True)):
        ##if we only want to see the positive correlations we then delete the edges with weight smaller than 0        
        if corr_direction == "positive":
            ####it adds a minimum value for correlation. 
            ####If correlation weaker than the min, then it deletes the edge
            if weight["weight"] <0 or weight["weight"] < min_correlation:
                H.remove_edge(stock1, stock2)
        ##this part runs if the corr_direction is negative and removes edges with weights equal or largen than 0
        else:
            ####it adds a minimum value for correlation. 
            ####If correlation weaker than the min, then it deletes the edge
            if weight["weight"] >=0 or weight["weight"] > min_correlation:
                H.remove_edge(stock1, stock2)
    return(H)

In [0]:
"""
 Inputs a data list

 Returns new dictionary with the corresponding correlation matrix, graph, and results for each mouse and condition 
"""

def make_graphs(data_dict, direction, min_cor):
    print("[INFO] making graph dictionary.")
    # initialize dictionaries
    edge_dict={}
    cor_dict={}
    FC_dict={}
    sd_dict={}
    graph_dict={}

    # loop through data
    for subj_id in data_dict:
      cor_data = data_dict[subj_id]['corr']
      #i=i.set_index(labels.ID)
      #i.rename(columns=labels.ID, inplace=True)
      edge_dict.setdefault(subj_id, []).append(cor_data)
      cor_matrix = np.asmatrix(cor_data)
      x=abs(cor_matrix)
      mu=x.mean()
      sd=x.std()
      cor_dict.setdefault(subj_id, []).append(x)
      FC_dict.setdefault(subj_id, []).append(mu)
      sd_dict.setdefault(subj_id, []).append(sd)
      G = nx.from_numpy_matrix(cor_matrix)
      #for i, nlrow in labels.iterrows():
          #G.node[i].update(nlrow[0:].to_dict())
      graph_dict.setdefault(key, []).append(G)
    new_dict={'edges':edge_dict, 'correlations':cor_dict, 'mean_FC':FC_dict,
              'stdev':sd_dict, 'graphs':graph_dict}
    return(new_dict)

## Make graphs

In [61]:
#Now we apply our two functions to make the new dictionary of graphs
#Options here are "positive" or "negative" and a threshold for the minimum edge strength (default = 0)

GRAPHS = make_graphs(data_dict, "positive", 0)
GRAPHS.keys()

[INFO] making graph dictionary.

dict_keys(['edges', 'correlations', 'mean_FC', 'stdev', 'graphs'])

### Visualize Results

In [80]:
print("[INFO] viewing the mean FC (average edge weight): \n")
mean_df = pd.DataFrame(GRAPHS['mean_FC']).T
mean_df.columns=["mean_FC"]
ICD.display(mean_df)

[INFO] viewing the mean FC (average edge weight):

     mean_FC
M1  0.874629
M2  0.259083
M3  0.164250